version: 2
jobs:
  build:
    working_directory: /esp-rs
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            docker build -t esp-rust .
